kind = "web"
previewPath = "/"
title = "FryCuisine"
version = "1.0.0"
id = "artifacts/frycuisine"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25898

[services.development]
run = "pnpm --filter @workspace/frycuisine run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/frycuisine", "run", "build" ]
publicDir = "artifacts/frycuisine/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25898"
BASE_PATH = "/"
